"""
crypto_core.kem
===============
Hybrid KEM-DEM (Key Encapsulation Mechanism + Data Encapsulation Mechanism).

Implements the correct asymmetric KEM flow as defined by NIST FIPS 203:

    Encryption (sender):
        1. Load recipient's public key.
        2. Call kem.encap_secret(public_key) → (kem_ciphertext, shared_secret)
        3. Derive AES key from shared_secret via HKDF-SHA256.
        4. Encrypt plaintext with AES-256-GCM using derived key.
        5. Build payload: kem_ciphertext + nonce + aes_ciphertext.

    Decryption (recipient):
        1. Load own private key.
        2. Parse payload → extract kem_ciphertext, nonce, aes_ciphertext.
        3. Call kem.decap_secret(kem_ciphertext) → shared_secret.
        4. Re-derive same AES key via HKDF-SHA256.
        5. Decrypt aes_ciphertext → plaintext.

Security notes:
    - shared_secret is NEVER used directly as AES key.
    - HKDF-SHA256 provides domain separation via the `info` field.
    - KEM ciphertext encapsulates entropy, not the AES key itself.
    - AAD binds the AES ciphertext to the KEM ciphertext to prevent substitution.

Supported algorithms:
    - ML-KEM-768 (NIST FIPS 203, Level 3) — default
    - HQC-128   (conditional, only if available in this liboqs build)
"""

import logging
from typing import Literal

from cryptography.hazmat.primitives.hashes import SHA256
from cryptography.hazmat.primitives.kdf.hkdf import HKDF

from liboqs_runtime import get_oqs_module, resolve_kem_name
from key_management.key_manager import decode_key, encode_key
from crypto_core.aes import aes_encrypt, aes_decrypt
from protocol.envelope import build_envelope, parse_envelope

logger = logging.getLogger(__name__)

_AES_KEY_LENGTH: int = 32   # bytes — AES-256
_HKDF_INFO      = b"encrypt-pqc-kem-v3-aes-key"

SupportedKEM = Literal["ML-KEM-768", "HQC-KEM"]


def _derive_aes_key(shared_secret: bytes) -> bytes:
    """
    Derives a 256-bit AES key from a KEM shared secret using HKDF-SHA256.

    This prevents direct use of the shared_secret as an AES key, providing
    domain separation and ensuring the derived key has full entropy even if
    the shared_secret has biases.

    Args:
        shared_secret: Raw bytes from KEM encap/decap (length varies by algo).

    Returns:
        32 bytes suitable for AES-256-GCM.
    """
    hkdf = HKDF(
        algorithm=SHA256(),
        length=_AES_KEY_LENGTH,
        salt=None,      # KEM shared_secret already has strong entropy
        info=_HKDF_INFO,
    )
    key = hkdf.derive(shared_secret)
    logger.debug("_derive_aes_key: shared_secret=%d bytes → aes_key=32 bytes",
                 len(shared_secret))
    return key


def kem_encrypt(plaintext: str, public_key_b64: str, ui_algo: SupportedKEM) -> str:
    """
    Encrypts plaintext using hybrid KEM-DEM with the recipient's public key.

    Args:
        plaintext:      UTF-8 string to encrypt.
        public_key_b64: Recipient's public key in base64 url-safe encoding.
                        Generated by key_management.key_manager.generate_kem_keypair().
        ui_algo:        Algorithm name as shown in UI ("ML-KEM-768" or "HQC-KEM").

    Returns:
        Base64-encoded envelope string (v3.0 payload).

    Raises:
        RuntimeError: if liboqs is unavailable or algorithm not in this build.
        ValueError:   if public_key_b64 is not valid base64.
    """
    oqs      = get_oqs_module()
    oqs_name = resolve_kem_name(ui_algo)
    pub_key  = decode_key(public_key_b64)

    logger.info("kem_encrypt: algo=%s, plaintext_len=%d, pub_key_len=%d",
                oqs_name, len(plaintext), len(pub_key))

    with oqs.KeyEncapsulation(oqs_name) as kem:
        kem_ciphertext, shared_secret = kem.encap_secret(pub_key)

    logger.debug("kem_encrypt: kem_ct=%d bytes, shared_secret=%d bytes",
                 len(kem_ciphertext), len(shared_secret))

    aes_key = _derive_aes_key(shared_secret)

    # AAD = kem_ciphertext to bind AES ciphertext to this specific KEM encapsulation
    nonce, aes_ciphertext = aes_encrypt(
        aes_key,
        plaintext.encode("utf-8"),
        aad=kem_ciphertext,
    )

    return build_envelope(
        kem_algo       = ui_algo,
        kem_ciphertext = kem_ciphertext,
        nonce          = nonce,
        aes_ciphertext = aes_ciphertext,
    )


def kem_decrypt(token: str, private_key_b64: str, ui_algo: SupportedKEM) -> str:
    """
    Decrypts a KEM-DEM envelope using the recipient's private key.

    Args:
        token:           Base64-encoded envelope produced by kem_encrypt().
        private_key_b64: Recipient's private key in base64 url-safe encoding.
        ui_algo:         Must match the algorithm used during encryption.

    Returns:
        Decrypted plaintext as UTF-8 string.

    Raises:
        RuntimeError: if liboqs is unavailable.
        ValueError:   if token is malformed, versions mismatch, key is wrong,
                      or data is tampered. Always fails closed — no silent fallback.
    """
    oqs      = get_oqs_module()
    oqs_name = resolve_kem_name(ui_algo)
    priv_key = decode_key(private_key_b64)

    envelope = parse_envelope(token)

    kem_ciphertext = envelope["kem_ct_bytes"]
    nonce          = envelope["nonce_bytes"]
    aes_ciphertext = envelope["aes_ct_bytes"]

    logger.info("kem_decrypt: algo=%s, kem_ct=%d bytes",
                oqs_name, len(kem_ciphertext))

    with oqs.KeyEncapsulation(oqs_name, secret_key=priv_key) as kem:
        shared_secret = kem.decap_secret(kem_ciphertext)

    logger.debug("kem_decrypt: shared_secret=%d bytes", len(shared_secret))

    aes_key = _derive_aes_key(shared_secret)

    plaintext_bytes = aes_decrypt(
        aes_key,
        nonce,
        aes_ciphertext,
        aad=kem_ciphertext,
    )

    return plaintext_bytes.decode("utf-8")
